# Site settings
title: Eland of Coding
header-img: img/home-bg.png
email: erinland05@gmail.com
copyright_name: eland05
description: > # this means to ignore newlines until "baseurl:"
  My journey into the world of programming.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eland05
learn_profile: eland05
email_username: erinland05@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
